// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHhcsUcUVe1XzqvEydf467Hj6qdApCGI',
    appId: '1:183383681747:web:6eed14f7922049e22bc226',
    messagingSenderId: '183383681747',
    projectId: 'authentication-df14b',
    authDomain: 'authentication-df14b.firebaseapp.com',
    storageBucket: 'authentication-df14b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBIUIIlZnv94WVFumy5GqVQrwFtImwGXw',
    appId: '1:183383681747:android:6f6bd8fdf0252eb62bc226',
    messagingSenderId: '183383681747',
    projectId: 'authentication-df14b',
    storageBucket: 'authentication-df14b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHE0Ud88lPfcqQCYmUS_9igA80wThB7n0',
    appId: '1:183383681747:ios:a184dbb37053d0292bc226',
    messagingSenderId: '183383681747',
    projectId: 'authentication-df14b',
    storageBucket: 'authentication-df14b.appspot.com',
    iosClientId: '183383681747-s19dn6g6fvt60bkmkrdgln0ktsufkrhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHE0Ud88lPfcqQCYmUS_9igA80wThB7n0',
    appId: '1:183383681747:ios:d38b1a65de4e38912bc226',
    messagingSenderId: '183383681747',
    projectId: 'authentication-df14b',
    storageBucket: 'authentication-df14b.appspot.com',
    iosClientId: '183383681747-ak0ruf3lakl7k62ml3t6ja2l18qph847.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
